### ISSUE TITLE
New anti-prespeed is a bit annoying

### ISSUE THREAD

**Issue by e-slut** [TotallyMehis/Influx-Timer#43]
If you jump too far back in the start zone it doesn't start your timer. I think a better way of doing this is setting the max velocity in the start zone to 300.

**Comment by TotallyMehis** [comment]
The default value should be -1. You didn't update the configs.

**Comment by e-slut** [comment]
Oh forgot xd

**Comment by e-slut** [comment]
I updated it still the same

**Comment by TotallyMehis** [comment]
Delete the prespeed keyvalues in influxruns/map.ini

**Comment by e-slut** [comment]
The problem is still there, this is what I mean by annoying https://streamable.com/m9rd1 if you jump inside the start zone at all the time won't start and all when it should be a legal start. Freshly zoned map btw following the new run format. @TotallyMehis

**Comment by TotallyMehis** [comment]
The reason was that when the run was loaded, it was assumed that the you want to use the current prespeed cvar values (eg. maxjumps 0). You then changed the max jumps to -1 and now when you change the map, it will save the maxjumps as 0 because it differs from -1 (current). This will no longer happen, BUT it already saved those values in the run files so you'll have to manually delete them unfortunately.

**Here's what you do**: you update to latest influx_prespeed, make sure influx_prespeed_maxjumps is set to -1 in cfg/influx/prespeed.cfg, change the map, remove prespeed_* keyvalues from influxruns/whatevermap.ini that you believe has these issues.

**Comment by e-slut** [comment]
Ok, it's good now thanks!
