### ISSUE TITLE
Movement Fix for Autostrafe

### ISSUE THREAD

**Issue by ghost** [TotallyMehis/Influx-Timer#9]
Like this:https://www.youtube.com/watch?v=wIrE-C9yZso

**Comment by Some1sm** [comment]
I guess this is not explained well but meh, in Influx you wont be able to go around the corners in any map because TAS wont fully follow your movement, it will do something like hsw or something but it wont actually do what its supossed to do, I guess adding a 1tick strafe silencer would fix it but i'm not 100% sure :D, thats the code from a CSGO cheat but it might help to understand it :)
`pCmd->forwardmove = 0.0f;
pCmd->sidemove = 0.0f;
 
if (pCmd->mousedx < 0)
{
    pCmd->sidemove = -450.0f;
}
else if (pCmd->mousedx > 0)
{
    pCmd->sidemove = 450.0f;
}
else
{
    if (AutoStrafeFlip)
    {
        pCmd->viewangles = Math->NormalizeAngle(QAngle(pCmd->viewangles.x, pCmd->viewangles.y - 1.0f, 0.0f));
        pCmd->sidemove = -450.0f;
        AutoStrafeFlip = false;
    }
    else
    {
        pCmd->viewangles = Math->NormalizeAngle(QAngle(pCmd->viewangles.x, pCmd->viewangles.y + 1.0f, 0.0f));
        pCmd->sidemove = 450.0f;
        AutoStrafeFlip = true;
    }
}`

**Comment by hoix** [comment]
The video above is of kz-endo's tas, the best TAS in CS:GO on a public server I think. It is only for whitelisted players at the moment because it has a bug in it at the moment, I don't know what though

**Comment by TotallyMehis** [comment]
The auto-strafe isn't final. The point was to make an auto-strafer that never loses speed. I'll eventually change it so that it'll follow your mouse once you've reached a certain yaw delta.

**Comment by nazakomu** [comment]
Just a few suggestions for the auto-strafe. Considering you want it so that the auto-strafer never loses speed - I presume you want it to max out to the cap/ceiling of velocity possible on whatever tickrate is specified, you should make sure that on 100tick that it can hit 650 units on the 6th jump because that is the maximum speed you can perform on the 6th jump of 100tick with any sort of tools. You should probably talk to Alkatraz (http://steamcommunity.com/id/127121325) about tools for TAS and maybe even collaborate if possible, he is very experienced and reliable in this department of bunnyhop. Do not be worried about how the movement visually looks because--most of the time--auto-strafers that perform better usually end up not being a silent auto-strafer.

EDIT: I've also realized that whenever I utilize the timescale in your TAS settings of the latest Git version, the replay bot makes the strafes look choppier in comparison to utilizing host_timescale on the stable versions. Another thing is that whenever I'm set at anything other than 1.00 on the new plugin, my zones lag, the weapon's bobbing animation is very choppy, and my ping goes up significantly (on a LAN server).

**Comment by XutaxKamay** [comment]
http://wiki.quakeworld.nu/QW_physics_air

to get the perfect angle depending on your velocity, you can do, angle = rad2deg(atanf(30 / velocity2d)); (30 comes from speed air cap)

but, there is some inaccurate issues with this you don't get 100% gain (99.8 or .9 _ i dont know why yet, i didn't investigate more), the better would be to convert the velocity vector to euler angles , then apply it to his y axis viewangle (viewangles.y = rad2deg(atanf(velocity.y/velocity.x)) i think), but you'll need to check if the guy is moving his mouse too much (otherwhise he won't turn like he wants)

**Comment by nazakomu** [comment]
Hmm. Alkatraz already has fully-functional TAS tools on his own server that gain 100% and I'm not entirely sure of what method succeeds to perform like-so.

**Comment by XutaxKamay** [comment]
like i said, rad2deg(atanf(velocity.y/velocity.x)) give you the perfect gain.

that's how i did it ( i know it looks bad)
qOldViewAngles, are just the player angles 

      `float sidespeed = _Cvar->FindVar( "cl_sidespeed" )->GetFloat();   
        Vector Velocity = _OffsetManualthis( EntVars->m_vecVelocity , Vector , LocalPlayer );
        QAngle qVelocity;
        float YVel = RAD2DEG(atan2f(Velocity.y,Velocity.x));
        float DifAngle = AngNormalize( qOldViewAngles.y - YVel );

        if ( !cvars[hack_autostrafer_circle]->GetBool() )
        {
            cmd->sidemove = sidespeed;

            if ( DifAngle > 0.0f )
                cmd->sidemove = -sidespeed;

///COPIED FROM SDK

            Vector		wishvel;
            float		fmove , smove;
            Vector		wishdir;
            float		wishspeed;
            Vector forward , right , up;

            AngleVectors( qOldViewAngles , &forward , &right , &up );  // Determine movement angles

            // Copy movement amounts
            fmove = cmd->forwardmove;
            smove = cmd->sidemove;

            // Zero out z components of movement vectors
            forward[2] = 0;
            right[2] = 0;
            VectorNormalizeFast( forward );  // Normalize remainder of vectors
            VectorNormalizeFast( right );    // 

            for ( int i = 0; i < 2; i++ )       // Determine x and y parts of velocity
                wishvel[i] = forward[i] * Velocity[0] + right[i] * Velocity[1];
            wishvel[2] = 0;             // Zero out z part of velocity

            VectorCopy( wishvel , wishdir );   // Determine maginitude of speed of move
            wishspeed = VectorNormalize( wishdir );

            //
            // clamp to server defined max speed
            //

            float flMaxSpeed = _OffsetManualthis( 0x0DA0 , float , LocalPlayer );

            if ( wishspeed != 0 && ( wishspeed > flMaxSpeed ) )
            {
                VectorScale( wishvel , flMaxSpeed / wishspeed , wishvel );
                wishspeed = flMaxSpeed;
            }

            float addspeed , currentspeed;
            float wishspd;

            wishspd = wishspeed;

            // Cap speed
            if ( wishspd > 30 )
                wishspd = 30;

            // Determine veer amount
            currentspeed = Velocity.Dot( wishdir );

            // See how much to add
            addspeed = wishspd - currentspeed;

            float gaincoeff = ( wishspd - abs( currentspeed ) ) / wishspd;

            Vector acceleration = addspeed * wishdir;

///COPIED FROM SDK

            static float OldGain = 0.f;

            float AngleGain = RAD2DEG( atanf( acceleration.y / acceleration.x ) );

            if ( !( ( OldGain < 0.0f  && AngleGain < 0.0f ) || ( OldGain > 0.0f  && AngleGain > 0.0f ) ) ) //this check tells you when the mouse player movement is higher than the autostrafer one, and decide to put it or not
                qOldViewAngles.y -= AngleGain;

            OldGain = AngleGain;

        }`

This is what  i've made into my hack, works fine,
Also if you're wondering why im not doing simply doing viewangles.y = rad2deg(atan2f(velocity.y,velocity.x)), it's because when the player angle difference is higher than the velocity angle's one, his direction will be shifted (so it will look like hsw and wont turn into right direction)

**Comment by ghost** [comment]
Closed because I wanted a silent strafe at first, now we got it
